### PR TITLE
Create index.html

### PR DESCRIPTION
**Pull request by rv2442**
want to add a js file too once this is merged

### CODE REVIEW

**Comment by rv2442** [comment]
const path = require('path');
const express = require('express');
const WebSocket = require('ws');
const app = express();

const WS_PORT  = 65080;
const HTTP_PORT = 80;

const wsServer = new WebSocket.Server({port: WS_PORT}, ()=> console.log(`WS Server is listening at ${WS_PORT}`));

/* Allows multiple clients to connect*/
let connectedClients = [];
wsServer.on('connection', (ws, req)=>{
    console.log('Connected');
    connectedClients.push(ws);

    ws.on('message', data => {
        connectedClients.forEach((ws,i)=>{
            if(ws.readyState === ws.OPEN){
                ws.send(data);
            }else{
                connectedClients.splice(i ,1);
            }
        })
    });
});

app.get('/client',(req,res)=>res.sendFile(path.resolve(__dirname, './client.html')));
app.listen(HTTP_PORT, ()=> console.log(`HTTP server listening at ${HTTP_PORT}`));



/* server.js */

**Comment by rv2442** [comment]
I tried to push through cli but was getting 
 
image

**Review by 19sajib — APPROVED** [review]

**Comment by 19sajib** [comment]
ok done

**Comment by 19sajib** [comment]
Please check the readme.md file properly,, full instruction there

**Pull request merged**
